import type { Agent, Deployment, HumanTask, Run, RuntimeEvent, Task } from "./types";

export const agents: Agent[] = [
  {
    id: 1,
    name: "support-agent",
    framework: "LangGraph",
    adapter: "langgraph-v1",
    version: "0.3.2",
    capabilities: ["invoke", "stream", "checkpoint", "human_interrupt"],
    deployments: 2,
    lastRunStatus: "succeeded",
    releasedAt: "2026-05-25T08:30:00Z",
  },
  {
    id: 2,
    name: "incident-triage",
    framework: "LangChain",
    adapter: "langchain-agent-v1",
    version: "0.2.0",
    capabilities: ["invoke", "tool_call", "artifact"],
    deployments: 1,
    lastRunStatus: "running",
    releasedAt: "2026-05-24T11:10:00Z",
  },
  {
    id: 3,
    name: "research-deepagent",
    framework: "DeepAgents",
    adapter: "deepagents-v1",
    version: "0.1.5",
    capabilities: ["invoke", "filesystem", "subagent"],
    deployments: 1,
    lastRunStatus: "failed",
    releasedAt: "2026-05-21T15:45:00Z",
  },
];

export const deployments: Deployment[] = [
  {
    id: 10,
    agent: "support-agent",
    version: "0.3.2",
    environment: "prod",
    desiredStatus: "active",
    runtimeStatus: "ready",
    instances: 6,
    runningRuns: 18,
    queueBacklog: 24,
    worker: "worker-prod-a",
    heartbeatAt: "2026-05-26T09:25:18Z",
    executionProfile: "prod-worker",
    modelGateway: "newapi-default",
  },
  {
    id: 11,
    agent: "incident-triage",
    version: "0.2.0",
    environment: "staging",
    desiredStatus: "paused",
    runtimeStatus: "degraded",
    instances: 2,
    runningRuns: 3,
    queueBacklog: 8,
    worker: "worker-stg-b",
    heartbeatAt: "2026-05-26T09:21:04Z",
    executionProfile: "staging-worker",
    modelGateway: "newapi-low-cost",
  },
  {
    id: 12,
    agent: "research-deepagent",
    version: "0.1.5",
    environment: "dev",
    desiredStatus: "draining",
    runtimeStatus: "warming_up",
    instances: 1,
    runningRuns: 1,
    queueBacklog: 2,
    worker: "worker-dev-a",
    heartbeatAt: "2026-05-26T09:23:40Z",
    executionProfile: "local-dev",
    modelGateway: "newapi-default",
  },
];

export const runs: Run[] = [
  {
    id: 100,
    agent: "support-agent",
    framework: "LangGraph",
    adapter: "langgraph-v1",
    version: "0.3.2",
    actor: "svc_support_api",
    status: "succeeded",
    latencyMs: 1840,
    costUsd: 0.042,
    startedAt: "2026-05-26T09:18:12Z",
    finishedAt: "2026-05-26T09:18:14Z",
    trigger: "api",
    deployment: "10",
    traceId: "trace_733a",
  },
  {
    id: 101,
    agent: "support-agent",
    framework: "LangGraph",
    adapter: "langgraph-v1",
    version: "0.3.2",
    actor: "viewer@example.com",
    status: "failed",
    latencyMs: 6420,
    costUsd: 0.088,
    startedAt: "2026-05-26T09:09:41Z",
    finishedAt: "2026-05-26T09:09:48Z",
    trigger: "compatibility",
    deployment: "10",
    traceId: "trace_91dc",
  },
  {
    id: 102,
    agent: "incident-triage",
    framework: "LangChain",
    adapter: "langchain-agent-v1",
    version: "0.2.0",
    actor: "ops@example.com",
    status: "running",
    latencyMs: 920,
    costUsd: 0.019,
    startedAt: "2026-05-26T09:25:02Z",
    trigger: "api",
    deployment: "11",
    traceId: "trace_601e",
  },
];

export const events: RuntimeEvent[] = [
  {
    sequence: 1,
    eventId: "run_01HX9KB6W4:1",
    type: "run.started",
    status: "succeeded",
    timestamp: "2026-05-26T09:09:41Z",
    summary: "Run accepted by dep_prod_support.",
  },
  {
    sequence: 2,
    eventId: "run_01HX9KB6W4:2",
    type: "task.leased",
    status: "running",
    timestamp: "2026-05-26T09:09:42Z",
    summary: "Task leased by worker-prod-a with fencing token 42.",
  },
  {
    sequence: 3,
    eventId: "run_01HX9KB6W4:3",
    type: "model.called",
    status: "succeeded",
    timestamp: "2026-05-26T09:09:44Z",
    summary: "newapi-default routed gpt-4.1-mini call.",
  },
  {
    sequence: 4,
    eventId: "run_01HX9KB6W4:4",
    type: "tool.called",
    status: "failed",
    timestamp: "2026-05-26T09:09:47Z",
    summary: "crm.update_ticket denied by approval policy.",
  },
  {
    sequence: 5,
    eventId: "run_01HX9KB6W4:5",
    type: "run.failed",
    status: "failed",
    timestamp: "2026-05-26T09:09:48Z",
    summary: "Run failed with POLICY_APPROVAL_REQUIRED.",
  },
];

export const tasks: Task[] = [
  {
    id: 1000,
    runId: 101,
    status: "dead_letter",
    attempt: 3,
    queue: "runtime.prod",
    workerId: "worker-prod-a",
    heartbeatAt: "2026-05-26T09:09:47Z",
    leaseUntil: "2026-05-26T09:10:17Z",
    fencingToken: 42,
    retryCount: 3,
    deadLetterReason: "POLICY_APPROVAL_REQUIRED",
  },
  {
    id: 1001,
    runId: 102,
    status: "leased",
    attempt: 1,
    queue: "runtime.staging",
    workerId: "worker-stg-b",
    heartbeatAt: "2026-05-26T09:25:12Z",
    leaseUntil: "2026-05-26T09:25:42Z",
    fencingToken: 7,
    retryCount: 0,
  },
];

export const humanTasks: HumanTask[] = [
  {
    id: 2000,
    source: "crm.update_ticket / run_01HX9KB6W4",
    risk: "high",
    status: "pending",
    assignee: "ops-admin",
    expiresAt: "2026-05-26T10:09:48Z",
  },
  {
    id: 2001,
    source: "deployment.restart / dep_staging_triage",
    risk: "medium",
    status: "pending",
    assignee: "runtime-admin",
    expiresAt: "2026-05-26T11:00:00Z",
  },
];
