apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dimoorun.fullname" . }}-config
data:
  DIMOORUN_RUNTIME_MODE: "enterprise"
  OBJECT_STORE_BACKEND: "minio"
  OBJECT_STORE_ENDPOINT_URL: "{{ .Values.objectStore.external.endpointUrl }}"
  OBJECT_STORE_BUCKET: "{{ .Values.objectStore.external.bucket }}"
  DIMOORUN_SANDBOX_MODE: "{{ .Values.sandbox.mode }}"
  DIMOORUN_SANDBOX_CPU_LIMIT: "{{ .Values.sandbox.cpuLimit }}"
  DIMOORUN_SANDBOX_MEMORY_LIMIT: "{{ .Values.sandbox.memoryLimit }}"
