apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dimoorun.fullname" . }}-console
spec:
  replicas: {{ .Values.console.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: dimoorun-console
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dimoorun-console
    spec:
      containers:
        - name: console
          image: "{{ .Values.image.repository }}-console:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.console.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dimoorun.fullname" . }}-console
spec:
  selector:
    app.kubernetes.io/name: dimoorun-console
  ports:
    - port: {{ .Values.console.port }}
      targetPort: {{ .Values.console.port }}
