apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dimoorun.fullname" . }}-server
  labels:
{{ include "dimoorun.labels" . | indent 4 }}
{{ include "dimoorun.serverLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
{{ include "dimoorun.serverLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "dimoorun.labels" . | indent 8 }}
{{ include "dimoorun.serverLabels" . | indent 8 }}
    spec:
      serviceAccountName: {{ include "dimoorun.fullname" . }}
      containers:
        - name: server
          image: "{{ .Values.image.repository }}-server:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
          envFrom:
            - configMapRef:
                name: {{ include "dimoorun.fullname" . }}-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.external.urlSecretRef }}
                  key: url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.external.urlSecretRef }}
                  key: url
            - name: OBJECT_STORE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.objectStore.external.secretRef }}
                  key: accessKey
            - name: OBJECT_STORE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.objectStore.external.secretRef }}
                  key: secretKey
          startupProbe:
            httpGet:
              path: {{ .Values.server.probes.startup.path }}
              port: {{ .Values.server.port }}
            failureThreshold: {{ .Values.server.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.server.probes.startup.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.server.probes.readiness.path }}
              port: {{ .Values.server.port }}
            periodSeconds: {{ .Values.server.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.server.probes.liveness.path }}
              port: {{ .Values.server.port }}
            periodSeconds: {{ .Values.server.probes.liveness.periodSeconds }}
          resources:
{{ toYaml (mergeOverwrite (deepCopy .Values.resources.defaults) .Values.server.resources) | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dimoorun.fullname" . }}-server
  labels:
{{ include "dimoorun.labels" . | indent 4 }}
{{ include "dimoorun.serverLabels" . | indent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
{{ include "dimoorun.serverLabels" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
