{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dimoorun.fullname" . }}-server
  labels:
{{ include "dimoorun.labels" . | indent 4 }}
{{ include "dimoorun.serverLabels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "dimoorun.serverLabels" . | indent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
