apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dimoorun.fullname" . }}-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: dimoorun-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dimoorun-worker
    spec:
      serviceAccountName: {{ include "dimoorun.fullname" . }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}-worker:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "dimoorun.fullname" . }}-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.external.urlSecretRef }}
                  key: url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.external.urlSecretRef }}
                  key: url
            - name: OBJECT_STORE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.objectStore.external.secretRef }}
                  key: accessKey
            - name: OBJECT_STORE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.objectStore.external.secretRef }}
                  key: secretKey
          resources:
{{ toYaml .Values.resources | indent 12 }}
